# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/APS_Lab3/Processors/ultimate_processor.cache/wt [current_project]
set_property parent.project_path E:/APS_Lab3/Processors/ultimate_processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/APS_Lab3/Processors/ultimate_processor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem E:/APS_Lab3/Processors/ultimate_processor.srcs/sources_1/new/i_ram.txt
read_verilog -library xil_defaultlib {
  E:/APS_Lab3/Processors/ultimate_processor.srcs/sources_1/new/defines_riscv.v
  E:/APS_Lab3/Processors/ultimate_processor.srcs/sources_1/new/alu.v
  E:/APS_Lab3/Processors/ultimate_processor.srcs/sources_1/new/psu_memory.v
  E:/APS_Lab3/Processors/ultimate_processor.srcs/sources_1/new/ram_memory.v
  E:/APS_Lab3/Processors/ultimate_processor.srcs/sources_1/new/risc_v.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/APS_Lab3/Processors/ultimate_processor.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files E:/APS_Lab3/Processors/ultimate_processor.srcs/constrs_1/new/constr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top risc_v -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef risc_v.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file risc_v_utilization_synth.rpt -pb risc_v_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
